### ISSUE TITLE
Radarr now also uses authenticationmethod external like prowlarr

### ISSUE THREAD

**Issue by rouke-broersma** [buildarr/buildarr-radarr#14]
See: https://github.com/buildarr/buildarr-prowlarr/issues/34
https://wiki.servarr.com/radarr/faq#forced-authentication

**Comment by rouke-broersma** [comment]
Note that this is not yet the case for sonarr but willl also come to sonarr in V4 if that ever ends up being released: https://wiki.servarr.com/sonarr/faq-v4#forced-authentication

**Comment by Callum027** [comment]
I'm still using Radarr V4 at the moment, which is why this hasn't come up for me.

I'll need to look through the changes to see if there is anything else I need to be aware of.

**Comment by Callum027** [comment]
https://github.com/buildarr/buildarr-radarr/issues/15

**Comment by Callum027** [comment]
Thanks for waiting. The fix for this issue has been released as:

* Python package: `buildarr-radarr==0.2.0`
* Docker container: `callum027/buildarr:0.7.0`

Please give the new version a try to check that it resolves your issue.

**Comment by rouke-broersma** [comment]
This works now, thanks!
